#!/bin/bash

if [ $# != 1 ]
then
	echo "Usage: "$0" process_name"
	exit 1
fi

while [ true ]
do
   sleep 1
   myPID=`pgrep $1`
   echo $myPID
   if [ `echo $myPID | wc -w` -eq 1 ]
   then 
	   iodisp $myPID
   fi
done